### ISSUE TITLE
Docker install via Compose

### ISSUE THREAD

**Issue by exy** [Domotrique/okovision_2023#8]
### Discussed in https://github.com/Domotrique/okovision_2023/discussions/2

<div type='discussions-op-text'>

<sup>Originally posted by **arkpoah** November 15, 2023</sup>
Hello,

Comme discuté, j'ai créé une installation pour Docker, voici la doc si certains sont intéressés.

- Déposer les sources d'Okovision dans un dossier `src`
- Créer un fichier `.env` pour les informations de connexion à la bdd
```
MYSQL_ROOT_PASSWORD="root_pwd"
MYSQL_DATABASE=okovision
MYSQL_USER=okovision
MYSQL_PASSWORD="okovision_pwd"
```
- Créer un fichier `docker-compose.yaml` 
```
version: '3.8'

services:
    mariadb:
      image: 'yobasystems/alpine-mariadb:latest'
      container_name: mariadb
      restart: always
      environment:
        MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
        MYSQL_DATABASE: ${MYSQL_DATABASE}
        MYSQL_USER: ${MYSQL_USER}
        MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      ports:
          - '3306:3306'
      volumes:
          - /var/lib/mariadb_docker/:/var/lib/mysql/

    php:
      container_name: php
      build: .
      volumes: 
           - /var/log/apache2/app:/var/log/apache2/
           - ${PWD}/src:/var/www/html/
      ports:
           - 8080:80
      depends_on:
          - mariadb
    cron:
      container_name: oko-cron
      build:
        context: .
        dockerfile: Dockerfile_cron
      volumes: 
           - ${PWD}/src:/var/www/html/

```
- Créer un fichier `logging.ini` afin de voir les erreurs php dans les logs
```
; log PHP errors to a file. E_ALL=32767
log_errors = on
error_reporting = 32767
error_log = /proc/1/fd/1
```
- Créer un fichier `Dockerfile`
```
FROM php:8.2-apache

# PHP
RUN apt-get update && apt-get upgrade -y
RUN apt-get install -y libpng-dev libonig-dev libicu-dev
RUN docker-php-ext-install gd intl mysqli
COPY logging.ini /usr/local/etc/php/conf.d/logging.ini
RUN mv "$PHP_INI_DIR/php.ini-production" "$PHP_INI_DIR/php.ini"
RUN sed -i 's/auto_start\ \=\ 0/auto_start\ \=\ 1/' "$PHP_INI_DIR/php.ini"

# Apache
RUN a2enmod rewrite
RUN service apache2 restart
```
- Créer le fichier `cron_entry.sh`
```
#!/bin/sh

# start cron
/usr/sbin/cron -f -l 8
```
- Créer un fichier `Dockerfile_cron`
```
FROM php:8.2-cli

RUN apt-get update && apt-get upgrade -y && apt-get install -y cron
RUN docker-php-ext-install mysqli
RUN echo "* */2 * * *	root	cd /var/www/html; /usr/local/bin/php -f cron.php > /dev/null" > /etc/cron.d/okovision

COPY cron_entry.sh /entry.sh
RUN chmod +x /entry.sh

CMD ["/entry.sh"]
```
- Exécuter la commande `docker-compose up -d`

Okovision sera accessible à cette adresse : http://[HOST_IP]:8080</div>
